# This configuration uses go templates
# You can use https://gotemplate.io/ to test your template configuration
version: 1
metrics:
  enabled: true
  listenAddr: ":6123"
  endpoint: "/metrics"
  tls:
    certificateFile: ""
    privateKeyFile: ""
sensors:
  - name: Xiaomi Mi Temperature and Humidity Monitor 2
    enabled: false
    input:
      transforms:
        - name: ble-to-mqtt
          properties:
            serviceDataKey: "0000fe95-0000-1000-8000-00805f9b34fb"
      mqtt:
        enabled: true
        topics:
          - ble_events/ServiceDataAdvertisement/LYWSD03MMC/#
        brokerUrls:
          - tcp://localhost:1883
        username: ""
        password: ""
        clientId: LYWSD03MMC_Subscriber
        keepAlive: 5
        connectRetryDelay: 5s
      memphis:
        enabled: false
        hostname: 127.0.0.1:6666
        username: bletomemphisconsumer
        password: yourpassword
        station: bletomemphis
        consumerName: bletomemphisconsumer
        pollInterval: 1s
        batchSize: 100
        headerPrefixes:
          path: ble-to-memphis/ServiceDataAdvertisement/*/LYWSD03MMC
    outputs:
      - mqtt:
          enabled: true
          topic: sensors/LYWSD03MMC/{{index .Properties "deviceName" }}/{{index .Properties "unit" | ToLower }}
          brokerUrls:
            - tcp://localhost:1883
          username: ""
          password: ""
          clientId: LYWSD03MMC_Publisher
          keepAlive: 5
          connectRetryDelay: 5s
          qos: 0
          retain: false
      - influxdb2:
          enabled: false
          url: "http://localhost:8086/"
          authToken: ""
          organizationId: ""
          bucket: sensors
          measurement: "{{ index .Properties \"unit\" }}"
          useGZip: true
          batchSize: 0
          tagMapping:
            name: "{{ index .Properties \"deviceName\" }}"
            type: "{{ index .Properties \"deviceType\" }}"
            macAddress: "{{ index .Properties \"deviceMacAddress\" }}"
            unit: "{{ index .Properties \"unit\" }}"
          fieldMapping:
            unit: "{{ index .Properties \"unit\" }}"
            value: "{{ index .Properties \"value\" | ToNumber }}"
      - prometheus:
          enabled: false
          metricsMapping:
            - name: |
                {{- index .Properties "unit" | ToLower -}}
                {{- if eq (index .Properties "unit") "Temperature" -}}
                _celsius
                {{- else if or (eq (index .Properties "unit") "Humidity") (eq (index .Properties "unit") "Battery") -}}
                _percent
                {{- end -}}
              description: "sensor value." # Templating supported
              namespace: "yasp"
              subsystem: "{{- index .Properties \"deviceType\" | ToLower -}}" # Templating supported
              labels:
                device: "{{- index .Properties \"deviceName\" -}}" # Templating supported on both keys and values
                deviceType: "{{- index .Properties \"deviceType\" -}}"
              type: Gauge # Templating supported
              value: "{{ index .Properties \"value\" | ToNumber }}" # Templating supported
              condition: ""  # Templating supported
    # Individual mapping per unit example
    #            - name: Temperature
    #              description: Temperature sensor value.
    #              namespace: ""
    #              subsystem: ""
    #              labels:
    #                device: "{{ index .Properties \"deviceName\" }}"
    #                deviceType: "{{ index .Properties \"deviceType\" }}"
    #              type: Gauge
    #              value: "{{ index .Properties \"value\" | ToNumber }}"
    #              condition: "{{ eq (index .Properties \"unit\") \"Temperature\" }}"
    #            - name: Humidity
    #              description: Humidity sensor value.
    #              namespace: ""
    #              subsystem: ""
    #              labels:
    #                device: "{{ index .Properties \"deviceName\" }}"
    #                deviceType: "{{ index .Properties \"deviceType\" }}"
    #              type: Gauge
    #              value: "{{ index .Properties \"value\" | ToNumber }}"
    #              condition: "{{ eq (index .Properties \"unit\") \"Humidity\" }}"
    #            - name: Battery
    #              description: Battery sensor value.
    #              namespace: ""
    #              subsystem: ""
    #              labels:
    #                device: "{{ index .Properties \"deviceName\" }}"
    #                deviceType: "{{ index .Properties \"deviceType\" }}"
    #              type: Gauge
    #              value: "{{ index .Properties \"value\" | ToNumber }}"
    #              condition: "{{- if eq (index .Properties \"unit\") \"Battery\" -}}true{{- else - }}false{{- end -}}"
    devices:
      - name: Your Sensor
        type: LYWSD03MMC
        properties:
          macAddress: "A4:C1:38:AB:CD:EF"
          encryptionKey: "0abcdef0000000000000000000000000"
  - name: P1P2 HVAC
    enabled: true
    input:
      mqtt:
        enabled: true
        topics:
          - "P1P2/R/P1P2MQTT/#"
        brokerUrls:
          - tcp://localhost:1883
        clientId: P1P2_Subscriber
        keepAlive: 5
        connectRetryDelay: 5s
    outputs:
      - prometheus:
          enabled: true
          metricsMapping:
            - name: "temperature"
              description: "p1p2 target temperature."
              type: Gauge
              value: "{{ index .Properties \"temperature\" | ToNumber }}"
              namespace: "yasp"
              subsystem: "p1p2"
              labels:
                device: "{{ index .Properties \"bridge\" }}"
            - name: "status"
              description: "p1p2 operation status."
              type: Gauge
              value: "{{ index .Properties \"status\" | ToNumber }}"
              namespace: "yasp"
              subsystem: "p1p2"
              labels:
                device: "{{ index .Properties \"bridge\" }}"
            - name: "testMode"
              description: "p1p2 test mode status."
              type: Gauge
              value: "{{ index .Properties \"testMode\" | ToNumber }}"
              namespace: "yasp"
              subsystem: "p1p2"
              labels:
                device: "{{ index .Properties \"bridge\" }}"
            - name: "errorCode"
              description: "p1p2 error code."
              type: Gauge
              value: "{{ index .Properties \"errorCode\" | ToNumber }}"
              namespace: "yasp"
              subsystem: "p1p2"
              labels:
                device: "{{ index .Properties \"bridge\" }}"
            - name: "mode"
              description: "p1p2 mode, 1 = cooling, 2 = heating."
              type: Gauge
              value: "{{ index .Properties \"modeId\" | ToNumber }}"
              namespace: "yasp"
              subsystem: "p1p2"
              labels:
                device: "{{ index .Properties \"bridge\" }}"
            - name: "fanSpeed"
              description: "p1p2 fan speed, 1 = low, 2 = medium, 3 = high."
              type: Gauge
              value: "{{ index .Properties \"fanSpeedId\" | ToNumber }}"
              namespace: "yasp"
              subsystem: "p1p2"
              labels:
                device: "{{ index .Properties \"bridge\" }}"
    devices:
      - name: Your Device
        type: p1p2
        properties:
          allowedPrefixes: "P1P2/R/P1P2MQTT/"
