version: 1
sensors:
  - name: Xiaomi Mi Temperature and Humidity Monitor 2
    input:
      transforms:
        - name: ble-to-mqtt
          properties:
            serviceDataKey: "0000fe95-0000-1000-8000-00805f9b34fb"
      mqtt:
        topic: ble_events/ServiceDataAdvertisement/LYWSD03MMC
        brokerUrls:
          - tcp://localhost:1883
        clientId: LYWSD03MMC_Subscriber
        keepAlive: 5
        connectRetryDelay: 5s
    outputs:
      - mqtt:
          topic: sensors/LYWSD03MMC/{{index .Properties "deviceName" }}/{{index .Properties "unit" | ToLower }}
          brokerUrls:
           - tcp://localhost:1883
          clientId: LYWSD03MMC_Publisher
          keepAlive: 5
          connectRetryDelay: 5s
    devices:
      - name: Your Sensor
        type: LYWSD03MMC
        properties:
          macAddress: "A4:C1:38:AB:CD:EF"
          encryptionKey: "0abcdef0000000000000000000000000"
